# These settings are synced to GitHub by https://probot.github.io/apps/settings/

repository:
  description: ANSI text styling
  homepage: "https://docs.rs/anstyle"
  topics: "rust cli color"
  has_issues: true
  has_projects: false
  has_wiki: false
  has_downloads: true
  default_branch: main

  # Preference: people do clean commits
  allow_merge_commit: true
  # Backup in case we need to clean up commits
  allow_squash_merge: true
  # Not really needed
  allow_rebase_merge: false

  allow_auto_merge: true
  delete_branch_on_merge: true

  squash_merge_commit_title: "PR_TITLE"
  squash_merge_commit_message: "PR_BODY"
  merge_commit_message: "PR_BODY"

labels:
  - name: "A-style"
    description: "Area: anstyle"
    color: '#f7e101'
  - name: "A-stream"
    description: "Area: anstream"
    color: '#f7e101'
  # Type
  - name: "C-bug"
    color: '#f5f1fd'
    description: "Category: Things not working as expected"
  - name: "C-enhancement"
    color: '#f5f1fd'
    description: "Category: Raise on the bar on expectations"
  # Status
  - name: "S-triage"
    description: "Status: New; needs maintainer attention."
    color: '#D3DDDD'
  - name: "S-blocked"
    description: "Status: Blocked on something else such as an RFC or other implementation work."
    color: '#D3DDDD'
  # Meta
  - name: "breaking-change"
    color: '#E10C02'
  - name: "E-help-wanted"
    color: '#02E10C'
    description: "Help wanted!"

# This serves more as documentation.
# Branch protection API was replaced by rulesets but settings isn't updated.
# See https://github.com/repository-settings/app/issues/825
#
# branches:
#   - name: main
#     protection:
#       required_pull_request_reviews: null
#       required_conversation_resolution: true
#       required_status_checks:
#         # Required. Require branches to be up to date before merging.
#         strict: false
#         contexts: ["CI", "Spell Check with Typos"]
#       enforce_admins: false
#       restrictions: null
